service: FailureInjectionLayer

provider:
  name: aws

layers:
  failureInjection:
    path: ./
    name: ${self:service}
    compatibleRuntimes:
      - python3.12
    retain: true

package:
  exclude:
    - ./**
  include:
    - python/**
